### ISSUE TITLE
Consensus peaks, clarification on their definition and impact of the -c option

### ISSUE THREAD

**Issue by AlexBlais74** [Genometric/MSPC#130]
Hello
I discovered MSPC and it seems to be quite useful for our work with peak calling in ATAC-seq datasets.

I have a question regarding the definition of "consensus peaks". It is not very clearly explained on the website:
https://genometric.github.io/MSPC/docs/method/consensus

The definition says 

> A consensus peak is created on a position of genome where is covered by at least one peak from the output sets of the processed replicates.

But in the output folders (each folder created for each of my replicate peak calls, I see multiple outputs (the "confirmed", "stringent", "true positives", etc). I am wondering which of those is used to generate the consensus list.

Secondly,  I noted the -c option, and its usage is again not very clearly explained. 

> -c <value>    Sets minimum number of overlapping peaks before combining p-values.

Does the -c value mean the number of replicates where the peak is in the "confirmed" output bed file? And is this a criteria for sending (or not sending) a given peak to the "consensus" bed file based on whether it passes this filter?

Thanks
Alex

**Comment by VJalili** [comment]
@AlexBlais74 you're right, the documentation needs further clarification. We'll do it as part of the website/docs overhaul: https://github.com/Genometric/MSPC/pull/127


>> A consensus peak is created on a position of genome where is covered by at least one peak from the output sets of the processed replicates.

>But in the output folders (each folder created for each of my replicate peak calls, I see multiple outputs (the "confirmed", "stringent", "true positives", etc). I am wondering which of those is used to generate the consensus list.

By the "output set" we mean a peak that is at least as significant as the weak threshold (`-w`), and has passed the combined stringency test (`-g`), and Benjamini-Hochberg multiple testing correction (`-a`). These are the peaks in the `TruePositive.bed` and `TruePositive_mspc_peaks.txt1` files. See may see the figure on [this](https://genometric.github.io/MSPC/docs/method/sets) page. 

The peaks given in the `TruePositive.bed` files are used to generate the consensus peaks. 


>> `-c` Sets minimum number of overlapping peaks before combining p-values.

> Does the -c value mean the number of replicates where the peak is in the "confirmed" output bed file? And is this a criteria for sending (or not sending) a given peak to the "consensus" bed file based on whether it passes this filter?

If a peak does not overlap with at least `c` peaks from the replicates (one peak per replicate), then that peak will be discarded (i.e., it will appear in the `Discarded.bed` file), and will not be used to compute the consensus peaks. For instance, when studying 3 replicates and when `c=3`, then the peaks that do not overlap with at least one peak from both replicates will be discarded.

The default value of `c=1`; hence, by default, the peaks that do not overlap with any other peak will be considered for combined stringency and BH-correction tests (and they will be used to compute the consensus peaks if they pass the combined stringency and BH tests).

**Comment by AlexBlais74** [comment]
Thanks for the explanation!
If I may, I would suggest updating the explanatory figure to reflect:
-the situation with multiple input BED files (I had a hard time making sense of the figure because it starts with a single box labelled "input", implying a single peak file);
-where each variable (-w -s -g -a -c ) is used (e.g. inside the "stringent" box, indicate "pvalue > s")
-how the "consensus" is derived.

I was not able to understand figure 3 of the paper to get how the algorithm works, but this may just be a reflection of my own limitations ;-)
Thanks for a great program.
Alex

**Comment by VJalili** [comment]
Thanks for the suggestion @AlexBlais74! 

I'm closing the issue as it seems the function of parameters are clear for you now. Please feel free to reopen if further clarification is needed.
