### ISSUE TITLE
Error while running the recent version of MSPC

### ISSUE THREAD

**Issue by MeriemBahda** [Genometric/MSPC#145]
Hi, 
After downloading the most recent version of MSPC, I tried running it but I got the following error message : 

 ` Error:
    An assembly specified in the application dependencies manifest (mspc.deps.json) was not found:
    package: 'System.Security.Cryptography.ProtectedData', version: '4.5.0'
    path: 'runtimes/win/lib/netstandard2.0/System.Security.Cryptography.ProtectedData.dll' `

**Comment by VJalili** [comment]
Thank you for reporting this. I updated the binaries for v5.0, please double-check if the issue resolved. 

Also, if you want to use the latest version, v5.1 is the current latest release.

**Comment by VJalili** [comment]
As per DMs, I guess this issue is resolved, please feel free to reopen if this issue occurs again.
