### ISSUE TITLE
Error while running the v5.0.0 and v5.1.0 releases of MSPC 

### ISSUE THREAD

**Issue by MeriemBahda** [Genometric/MSPC#146]
Hi, 

I downloaded the 2 latest releases of MSPC ( v5.0.0 and v5.1.0 ) using **Method B: Self-Contained** as shown in the MSPC installation tutorial. 
I downloaded afterwards the data from the demo.zip file. 
I then ran mspc using the command `.\mspc.exe -i .\rep*.bed -r bio -w 1e-4 -s 1e-8`

The MSPC program worked and returned the expected output as shown in the attached picture : 
<img width="823" alt="MSPC output" src="https://user-images.githubusercontent.com/65908120/109547798-d2ca7280-7a99-11eb-9410-8be13142bbc0.PNG">

But it also returned the following error
<img width="607" alt="Error" src="https://user-images.githubusercontent.com/65908120/109547010-e5907780-7a98-11eb-9f17-26c8c382c70f.PNG">

The files in my MSPC folder when i run the program are the following: 
* clrcompression.dll
* clrjit.dll
* Core.pdb
* coreclr.dll
* mscordaccore.dll
* mspc.exe
* mspc.pdb
* rep1
* rep2

Thank you,
Meriem

**Comment by VJalili** [comment]
@MeriemBahda do you see the exception before parsing data (i.e., above `.::...Parsing Samples...::.` or after `All process successfully finished`?

**Comment by MeriemBahda** [comment]
@VJalili 
Both actually! 
<img width="608" alt="Error 2" src="https://user-images.githubusercontent.com/65908120/109550184-ef1bde80-7a9c-11eb-9fe9-0cbfe0092506.PNG">
The error is shown several times before ` .::...Parsing Samples...::.` and once after ` All process successfully finished`

**Comment by VJalili** [comment]
@MeriemBahda Unfortunately I am not able to reproduce this error. This error can arise if the `log4net` configuration is not correctly set in `app.config`; however, interestingly we're not creating/using `app.config`. Therefore, I doubt there might be a problem with your `mspc` installation; e.g., extracting different versions to a common folder.

Maybe deleting your local `mspc` folder and reinstalling it would help as it will give you a clean installation.

**Comment by MeriemBahda** [comment]
@VJalili I deleted the `mspc` folder and reinstalled the program as suggested, and here's what I got : 

- When I installed mspc using the **Method A: Framework Dependent**, the program ran correctly and I didn't get any error! 

- When I installed mspc using the **Method B: Self-Contained**, I got the same error as before! 

Thank you!

**Comment by VJalili** [comment]
@MeriemBahda As per DMs, I assume this issue is resolved, please feel free to reopen if you face this error again.
