### ISSUE TITLE
The number of consensus peaks is greater than that of individual replicates?

### ISSUE THREAD

**Issue by nzx9581** [Genometric/MSPC#162]
Dear developers,

First, thanks for providing us with such a great package. I wanted to find some "common" peaks around 5 biological replicates of a sample with the sample command you presented in the manual: `$MSPC/mspc -i ATAC_D3_*.narrowPeak -w 1e-4 -s 1e-8 -r bio -o D3`. However, I am confused about the consensus peak file which gave me a strange value that is greater than the number of peaks of any replicate. Typically, the number of common peaks should be less than individual replicate, right? I don't know if it is a normal result, or I used inappropriate parameters? Could you please give me some suggestions to solve the problem? Thanks in advance!

> Number of peaks (5 replicates)
> 53639 ATAC_D3_1_peaks.narrowPeak
> 69989 ATAC_D3_2_peaks.narrowPeak
> 152633 ATAC_D3_3_peaks.narrowPeak
> 68203 ATAC_D3_4_peaks.narrowPeak
> 95279 ATAC_D3_5_peaks.narrowPeak

> Number of common peaks (MSPC results)
> 171405 ConsensusPeaks.bed

> Here is some background info：
> ref genome: hg19
> peak calling: macs2

**Comment by VJalili** [comment]
Thanks for using MSPC! 

**The definition of consensus/common peaks between replicates varies depending on your experimental setup.** Consider the following example: 

```
Replicate 1: 
chr1    10    20    peak_1    80

Replicate 2:
chr1    15    25    peak_2    88
```

In this example, the interval `chr1    10    25` may seem a good common interval; however, some cases as the following require more thoughtful consideration: 

```
Replicate 1: 
chr1    10    20    peak_1    80

Replicate 2:
chr1    30    40    peak_2    88
```

In this example, with all default parameters, MSPC may identify both `chr1    10    20` and `chr1    30    40` as "consensus" intervals, which is what happening in your run. You may interpret this as "my experiment has two biological replicates which show strong binding affinities at `chr1 10 20` and `chr1  30  40`; hence, I've two strong binding sites in my experiment (i.e., the consensus regions across my replicates)."

The ["consensus" peaks](https://genometric.github.io/MSPC/docs/method/consensus) are the union of [confirmed peaks](https://genometric.github.io/MSPC/docs/method/sets#confirmed). In your case, you have non-overlapping confirmed peaks across replicates (similar to the above example), hence, the number of peaks in `ConsensusPeaks.bed` is more than individual replicates. 

_In order to provide the MSPC arguments with more sensible values for your setup, I'd suggest you to decide what would be an ideal _consensus_ peak for your study, and adjust MSPC arguments accordingly._ For instance, do you expect to see a binding site across all the replicates? then set [`-c 100%`](https://genometric.github.io/MSPC/docs/cli/args#c).

Note that adjusting `-c` will impact all MSPC's output; hence, if the per-sample output with the default value of `-c` works for your study and you're only interested in adjusting `-c` for `ConsensusPeaks.bed`, then I'd suggest you to run MSPC twice, once with default value of `-c` to use the per-sample output, and once with the adjusted `-c` for the `ConsensusPeaks.bed`.

**Comment by VJalili** [comment]
I hope my explanation clarified it; closing the issue, but please feel free to reopen if you have further questions.
