### ISSUE TITLE
How do I run the self-contained version?

### ISSUE THREAD

**Issue by sufyazi** [Genometric/MSPC#189]
Hi authors! Thank you for developing this neat little program. However, I have an problem that is not sufficiently documented in the program's wiki (at least not that I could find). I am not able to install .NET for the machine I am planning to run MSPC on because I would be working with a remote HPC cluster. I followed the instruction to install the self-contained version here https://genometric.github.io/MSPC/docs/installation/ but I am unsure as to how to run the program? There are only .pdb files in the generated directory. How do I invoke the command on CLI?

**Comment by VJalili** [comment]
Hello @sufyazi. 

Can you please try the following steps (I assume you're running on Linux Ubuntu): 

```shell
$ wget -O mspc.zip "https://github.com/Genometric/MSPC/releases/latest/download/linux-x64.zip"
$ unzip mspc.zip -d mspc
$ cd mspc
$ chmod 777 mspc
$ ./mspc --help
```

**Comment by sufyazi** [comment]
Hi @VJalili ! Thank you! The steps worked perfectly!

As a non-programmer scientist, the steps you outlined in the README was not clear for the self-contained installation (as I wasn't sure what the `mspc` file was in the unzipped directory and I couldn't find the .dll file which is used to invoke the program using `dotnet`). My suggestion is for you to add these steps in the wiki for future users who might not very tech-savvy like I am. 😄 

Thanks again for this neat software. Feel free to close this issue.

**Comment by VJalili** [comment]
Glad it worked. I updated the docs; I hope that clarifies. 

I'm closing this issue, and please feel free to re-open it if it is still unclear.
