### ISSUE TITLE
C argument does not accept percentage

### ISSUE THREAD

**Issue by sufyazi** [Genometric/MSPC#191]
While running MSPC, I wanted to specify 50% for the `c` argument on `rmspc` (from Bioconductor), as described [here](https://genometric.github.io/MSPC/docs/cli/args#c). However, the program threw me a warning `Warning: Invalid C=50, it is set to C=5.` and proceeded to use `5` as the parameter value for the run.

**Context:** I had 5 biological replicated input peak files. The code I use to run `rmspc` specifically was as follows:

```
results <- mspc(input = input_paths, replicateType = "Bio", stringencyThreshold = 1e-8, weakThreshold = 1e-4, gamma = 1e-8, keep = TRUE, multipleIntersections = "Lowest", c = 50, alpha = 0.05, inputParserConfiguration = parser_json, outputPath = output_path)

```

Is it because I did not use % symbol? I removed it because my VSCode linter disliked that symbol there so I thought it is going to error out if I run the command. 

Tangential question: Considering the robustness of the MSPC analysis under the hood, do you have any recommendation for the value of C? Would setting it to the number of input samples be too stringent/remove potentially `true` peaks? The default setting is `1`; is there any justification for this design decision that I am not seeing?

**Comment by VJalili** [comment]
You need to use `%` if you want to specify the percentage of input as the value of `c`. Please see [this example](https://genometric.github.io/MSPC/docs/cli/args#c).

> Tangential question: Considering the robustness of the MSPC analysis under the hood, do you have any recommendation for the value of C? Would setting it to the number of input samples be too stringent/remove potentially true peaks? The default setting is 1; is there any justification for this design decision that I am not seeing?

Does [this](https://github.com/Genometric/MSPC/issues/150#issuecomment-817353537) help?

**Comment by sufyazi** [comment]
Hi Vahid, the link to answer my second question helped a lot! It makes so much sense and does tally with how I understood the design based from what I have read in your paper and documentation. Thank you.

I reran the command with the % symbol and it worked. Appreciate the help! Feel free to close this issue.

**Comment by VJalili** [comment]
Awesome! glad those were useful @sufyazi! 

I am closing this issue, and please feel free to re-open it if needed.
