### ISSUE TITLE
Problem about "Invalid culture info"

### ISSUE THREAD

**Issue by xiagjt** [Genometric/MSPC#192]
Hi! Recently I want to run the MSPC software to merge the peaks generated by MACS2 form DAP-Seq data. However, When I test the program using the demo data, I encountered an issue about wrong Invalid culture info as following:
![image](https://user-images.githubusercontent.com/21986615/226282996-396dc8e6-f326-4011-9220-2a554cdba78c.png)

I Tried to add a parser configuration using parameter "-p";
![image](https://user-images.githubusercontent.com/21986615/226283253-6bb5d9c0-837e-4af4-af76-97957c38a78d.png)
However, it does not work. thus, please help me to figure it out. Thanks.

**Comment by VJalili** [comment]
Hello, @xiagjt. 

Please see this [context on the Culture](https://genometric.github.io/MSPC/docs/cli/parser/#culture-info) if you are interested in how they impact MSPC. 

Could you please try `zh-Hans` or `zh-Hant` for Chinese Culture? 

> There are two culture names that contradict this rule. The cultures Chinese (Simplified), named zh-Hans, and Chinese (Traditional), named zh-Hant, are neutral cultures. The culture names represent the current standard and should be used unless you have a reason for using the older names zh-CHS and zh-CHT. [[REF](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-7.0)]

I noticed MSPC docs reference an outdated list of cultures for valid values. I'll update the documentation to refer to the correct Culture values.

**Comment by xiagjt** [comment]
Dear sir, thanks for your kind response.  I tried the zh-Hans and zh-Hant in the JSON file. However, it also failed with the same error. 
![image](https://user-images.githubusercontent.com/21986615/226493592-82f392c3-c2cb-443a-ab9c-5cb75125f689.png)
![image](https://user-images.githubusercontent.com/21986615/226493639-43a2bdaf-3d35-487d-b5ba-ca5a3004df3b.png)

**Comment by VJalili** [comment]
Referring to the following part of the screenshot you shared: 

```
Error: Invalid culture info. (Parameter 'value')
Actual value was zh-CN.
```

You have this error in both calls of MSPC, even though the JSON file you shared has other Culture info. Could you please make sure you are referencing the correct `config.json`? You may try giving the absolute/full path of the file (e.g., `/home/files/config.json` instead of `config.json`).

**Comment by xiagjt** [comment]
Hi, I have found the error which was actually due to the mistake in my Linux system. The command "export LANG=zh-Hans-CN" has resolved the problem. Thanks again for your help.

**Comment by xiagjt** [comment]
Hi. Another question about the option "--multipleIntersections": the lowest p-value refers to the -log10(P) format or just P value?

**Comment by VJalili** [comment]
Glad the issue was resolved. 


> Hi. Another question about the option "--multipleIntersections": the lowest p-value refers to the -log10(P) format or just P value?

It is applied to the `p-value`. 

The following lines of the code are when this parameter is applied.

https://github.com/Genometric/MSPC/blob/1f3700b2667f873616a5df34a13d1fd2719f5df3/Core/Functions/Processor.cs#L260-L264
