### ISSUE TITLE
Problem on ubuntu24 - no detected peaks

### ISSUE THREAD

**Issue by EvyDuvernois** [Genometric/MSPC#212]
Dear MSPC community
I am trying to use MSPC on my new laptop (ubuntu 24) and I have problem I never encountered. I followed the Self-Contained Method to install it (version 6). With my test bed files, no peaks are detected 

```
.::...Parsing Samples....::.
# Filename Read peaks# Min p-value Mean p-value Max p-value
---- -------------------- ----------- ----------- ------------ -----------
1/2 tt1 0 0,000E+000 NaN 0,000E+000
2/2 tt2 0 0,000E+000 NaN 0,000E+000

.::..Analyzing Samples...::.
[1/4] Initializing
[2/4] Processing samples
└── 0/0 (NaN) peaks
[3/4] Performing Multiple testing correction
[4/4] Creating consensus peaks set
```

When I try the test files provided by the demo zip folder, I have only few detected peaks 
```
./mspc -i rep*.bed -r bio -w 1e-4 -s 1e-8
Export Directory: xxxx/mspc/session_20240927_125843874

.::...Parsing Samples....::.
   #	            Filename	Read peaks#	Min p-value	Mean p-value	Max p-value	
----	--------------------	-----------	-----------	------------	-----------	
 1/2	                rep1	        322	 0,000E+000	  2,336E-003	 1,000E-002	
 2/2	                rep2	        548	 0,000E+000	  5,585E-005	 1,000E-003	

.::..Analyzing Samples...::.
[1/4] Initializing
[2/4] Processing samples
  └── 746/746	(100,000 %) peaks processed
[3/4] Performing Multiple testing correction
[4/4] Creating consensus peaks set

.::....Saving Results....::.

.::..Summary Statistics..::.
   #	            Filename	Read peaks#	Background	    Weak	Stringent	Confirmed	Discarded	TruePositive	FalsePositive	
----	--------------------	-----------	----------	--------	---------	---------	---------	------------	-------------	
 1/2	                rep1	        322	  24,534 %	56,832 %	 18,634 %	 49,689 %	 25,776 %	    49,689 %	      0,000 %	
 2/2	                rep2	        548	   8,212 %	75,547 %	 16,241 %	 85,949 %	  5,839 %	    85,949 %	      0,000 %	

.::.Consensus Peaks Count.::.
630


Elapsed time: 00:00:09.5912597
All processes successfully finished.

```

I tried to install the new version of MSPC on an older computer (debian 5). Same command lines to install, same command lines to launch. With the same input files, I obtained coherent data...

```
./mspc -i rep*.bed -r bio -w 1e-4 -s 1e-8
Export Directory: xxx/mspc/session_20240927_130445400

.::...Parsing Samples....::.
   #	            Filename	Read peaks#	Min p-value	Mean p-value	Max p-value	
----	--------------------	-----------	-----------	------------	-----------	
 1/2	                rep1	     53,697	 2.239E-074	  1.085E-003	 1.000E-002	
 2/2	                rep2	     37,717	 5.370E-301	  1.520E-004	 9.550E-003	

.::..Analyzing Samples...::.
[1/4] Initializing
[2/4] Processing samples
  └── 60,004/60,004000%)(100.000%) peaks processed
[3/4] Performing Multiple testing correction
[4/4] Creating consensus peaks set

::....Saving Results....::.  

.::..Summary Statistics..::.
   #	            Filename	Read peaks#	Background	    Weak	Stringent	Confirmed	Discarded	TruePositive	FalsePositive	
----	--------------------	-----------	----------	--------	---------	---------	---------	------------	-------------	
1/2                    rep1         53,697        47.045%       42.948%          10.006%         26.836%         26.119%            26.836%           0.000%   
2/2                    rep2         37,717        16.300%       50.354%          33.346%         43.482%         40.218%            43.482%           0.000%   

.::.Consensus Peaks Count.::.
17,290
```

EDIT : I firstly suspected a problem with .NET but I tried with different versions (8 - 6 - 5) and it is still the same. I also tried with the R package... same results. 

Any ideas?

**Comment by VJalili** [comment]
Hello, thanks for reporting this! 

This might be related to the differences between system culture or locale or your new Ubuntu machine and the machine you used to generate the files. For instance, in the example outputs you shared from your new and old machines, the new machine uses a comma (`,`) as a decimal separator, while the old machine uses a dot (`.`) for this purpose.

Ideally, your BED files should be culture-invariant, but some tools may add culture-related info to your BED files that will cause issues such as this when the files are used on a system with different culture settings. 

I suggest taking either of the following steps to rule out the possibility of system culture differences: 
* **Option 1:**  Change the locale on your new machine to match your old machine;
* **Option 2:** Configure MSPC to read files using the system culture of your old machine instead of the system default on the new machine. You may refer to [this documentation](https://genometric.github.io/MSPC/docs/cli/parser/#culture-info).

**Comment by EvyDuvernois** [comment]
Thank you so much for your prompt response, and sorry for the delay to answer back. 
I've just tested with a quick parser file like
{
   "Culture":"en-US"
}
and IT WORKED!!!
I did not notice the difference in the culture inside the different outputs I get. I only tested changing commas into dots in my input files and it did not work.

**Comment by VJalili** [comment]
Thanks for keeping me updated, and I am glad the solution worked for you. 

I am closing this issue since it seems it is resolved, but please feel free to reopen it if you continue seeing this issue.
