### ISSUE TITLE
Unhandled Exception:

### ISSUE THREAD

**Issue by EllieDuan** [Genometric/MSPC#81]
Thanks for this software! it runs super fast!
I got a message that saying dotnet is quit unexpectedly.
I thought it run through since all fold is generated. But I checked the log output has this message in the middle, showed up 2 times. 
I rerun it, the same. 
Can you help me with it? Thank you!

Only the "Summary statistics" was missing from these 2 files, so I guess it worked?
```
Unhandled Exception: System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Genometric.MSPC.CLI.SummaryStats.TruncateString(String value, Int32 maxLength)
   at Genometric.MSPC.CLI.SummaryStats.RenderRow(Int32 columnwidth, String[] columns)
   at Genometric.MSPC.CLI.SummaryStats.Create(List`1 samples, Dictionary`2 samplesDict, ReadOnlyDictionary`2 results, ReadOnlyDictionary`2 consensusPeaks, List`
1 exportedAttributes)
   at Genometric.MSPC.CLI.Program.Main(String[] args)
./6.14.19_MSPC_mac2_reps.sh: line 28: 33841 Abort trap: 6           dotnet /Users/ellie/Downloads/mspc_v3.3/CLI.dll -i ${line}*.bed -r bio -s 1E-8 -w 1E-4 -g 1E
-8 -c 2 -a 0.05 -m lowest
```

**Comment by VJalili** [comment]
Thanks for reporting this issue, @EllieDuan 

The PR https://github.com/Genometric/MSPC/pull/83 should fix this issue. 

Also, I created a patch release until `v4` is ready, you may download this patch release from [releases page](https://github.com/Genometric/MSPC/releases/tag/v3.3.1).

> Only the "Summary statistics" was missing from these 2 files, so I guess it worked?

Yes, because summary statistics are generated after replicates are merged, hence it does not affect rescuing peaks or creating consensus peaks.

**Comment by VJalili** [comment]
@EllieDuan Please feel free to reopen this issue if you still experience the same/similar issues.

**Comment by EllieDuan** [comment]
Thank you for checking out!
I have to copy all files in v3.3.1 folder to v.3.3 because the GeUtilities. System. ects are missing in the v3.3.1 folder, and I got this message:
```
Error:
  An assembly specified in the application dependencies manifest (CLI.deps.json) was not found:
    package: 'Genometric.GeUtilities', version: '5.3.0'
    path: 'lib/netcoreapp2.0/GeUtilities.dll' 
```

v3.3.1 runs great without bug after I merge it to v3.3!
Thank you!

**Comment by VJalili** [comment]
@EllieDuan Thanks for letting me know, I just fixed the released package.
