### ISSUE TITLE
Incorrect decimal separator

### ISSUE THREAD

**Issue by omorante** [Genometric/MSPC#96]
Using the software with different language configurations, I have detected a new issue. 

When I use my PC in Spanish (with decimal separator ","), MSPC is not able to detect the typical "." separator, which is use in the output of MACS2. If a -log10(pvalue) is 5.454, for example, MSPC detects 10^-5454. Moreover, as MSPC does not report an error, you could use the incorrect result. The only way to make it work properly is change the language or change the separator in the bed files.

I don't know nothing about .NET, but it would be great if you can force the separator to be always a point, regardless of the system language.

Best regards and thanks for the software.

**Comment by VJalili** [comment]
A good point, thanks for reporting it. We can incorporate [globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0) into MSPC parser.

Would it be possible for you to share a few lines of your BED file as an example?

**Comment by 4octavio4** [comment]
Yes, of course:

`chr1	906570	908082	ERX1302236.macs2_peak_call_peak_2	4.43063
chr1	955103	958028	ERX1302236.macs2_peak_call_peak_6	5.30005
chr1	1000441	1001319	ERX1302236.macs2_peak_call_peak_10	4.91812
chr1	1038982	1040743	ERX1302236.macs2_peak_call_peak_14	5.77528
chr1	1325573	1325870	ERX1302236.macs2_peak_call_peak_29	6.35090
chr1	1345199	1345675	ERX1302236.macs2_peak_call_peak_30	4.57723
chr1	1397908	1398281	ERX1302236.macs2_peak_call_peak_34	4.69618
chr1	1597242	1598380	ERX1302236.macs2_peak_call_peak_38	5.08147
chr1	1606767	1607070	ERX1302236.macs2_peak_call_peak_40	5.31424
chr1	1616639	1617394	ERX1302236.macs2_peak_call_peak_42	4.45772`

**Comment by VJalili** [comment]
@omorante I made a _preview_ release of the upcoming `v4`: https://github.com/Genometric/MSPC/releases/tag/v4.0.0-preview1

This release should have fixed the issue you're facing. 

Documentation is updated to explain how to specify culture information, if required. You may access them here: https://github.com/Genometric/MSPC/blob/dev/docs/cli/parser.md#culture-info

The [website](https://genometric.github.io/MSPC/) will be updated when a stable version of `v4` is release.

Please use this preview release, and let me know if it fixes the issue you've been facing.

**Comment by VJalili** [comment]
@omorante [`v4` is released](https://github.com/Genometric/MSPC/releases/tag/v4.0.0) and I believe it resolves the issue you've been facing. Therefore, I am closing this issue. Please feel free to reopen if it is not properly resolved.
